# Stage 4 — Rentals, Payments and Analysis

# 4.1 Determine the total number of rentals.

# 4.2 Determine which customer made the highest number of rentals.

# 4.3 Find the 10 customers who spent the most money.

# 4.4 Calculate the company's total revenue.

# 4.5 Calculate the revenue generated by each store.

# 4.6 Determine which staff member processed the highest total payment amount.

# 4.7 Find the most frequently rented films.

# 4.8 Find films that have never been rented.

# 4.9 Determine the month with the highest revenue.

# 4.10 Prepare a report showing: month → number of rentals → revenue.